### ISSUE TITLE
require('addon.node') results in error: module not found

### ISSUE THREAD

**Issue by corymickelson** [cmake-js/cmake-js#109]
I've been using cmakejs for a linux project for a while now without issue (for the most part), I recently had to add windows as a target platform, I've got the build working, and cmake-js finishes with the message: build succeeded, but when I try and require the module (on windows) I get this error: 
```
> require('build/Debug/npdf.node')
Error: Cannot find module 'build/Debug/npdf.node'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
```
CMakeLists.txt
```CMake
cmake_minimum_required(VERSION 3.8)

project(npdf)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_CXX_VISIBILITY_PRESET hidden)
set(CMAKE_VISIBILITY_INLINES_HIDDEN)
#set(CMAKE_CXX_FLAGS "-fsanitize=address")

# set(CMAKE_CXX_FLAGS -fPIC)
# Use the below command for building on windows
# cmake-js build -D --CDCMAKE_TOOLCHAIN_FILE=C:\SRCS\VCPKG\SCRIPTS\BUILDSYSTEMS\VCPKG.CMAKE --CDLIBCRYPTO_LIBRARY_NAMES=libeay32 --CDLIBSSL_LIBRARY_NAMES=ssleay32 --CDPODOFO_LIBRARY=C:\Users\micke\CMakeBuilds\4c25184c-e5d2-673f-92ce-a630b81f074c\install\x86-Release\lib\podofo.lib --CDPODOFO_INCLUDE_DIR=C:\Users\micke\CMakeBuilds\4c25184c-e5d2-673f-92ce-a630b81f074c\install\x86-Release\include
set(NAPI_CPP_EXCEPTIONS "yes")
if (MSVC)
    #set(PODOFO_LIBRARY "C:\\Users\\micke\\CMakeBuilds\\4c25184c-e5d2-673f-92ce-a630b81f074c\\install\\x86-Release\\lib\\podofo.lib")
    #set(PODOFO_INCLUDE_DIR "C:\\Users\\micke\\CMakeBuilds\\4c25184c-e5d2-673f-92ce-a630b81f074c\\install\\x86-Release\\include")
    set(CMAKE_CXX_FLAGS /EH)
    set(CMAKE_CXX_FLAGS /EHsc)
	message(WARNING "Using PoDoFo Library: ${PODOFO_LIBRARY}")
	message(WARNING "Using PoDoFo include dir: ${PODOFO_INCLUDE_DIR}")
endif (MSVC)

file(GLOB SOURCE_FILES
        "src/*.h"
        "src/*.cc"
        "src/base/*.cc"
        "src/base/*.h"
        "src/doc/*.h"
        "src/doc/*.cc"
        "src/crypto/*.h"
        "src/crypto/*.cc" )

add_library(${PROJECT_NAME} SHARED ${SOURCE_FILES})
set_target_properties(${PROJECT_NAME} PROPERTIES PREFIX "" SUFFIX ".node")

find_package(OpenSSL REQUIRED)

target_include_directories(${PROJECT_NAME} PRIVATE
        ${CMAKE_SOURCE_DIR}/node_modules/node-addon-api
        ${CMAKE_SOURCE_DIR}/node_modules/node-addon-api/src
        ${CMAKE_SOURCE_DIR}/include
        ${OPENSSL_INCLUDE_DIR}
        ${CMAKE_JS_INC})
target_link_libraries(${PROJECT_NAME} PRIVATE ${CMAKE_JS_LIB} ${OPENSSL_LIBRARIES})

message(WARNING "Openssl version: ${OPENSSL_VERSION}")

if (MSVC)
    add_definitions(-DUSING_SHARED_PODOFO=1)
    target_include_directories(${PROJECT_NAME} PRIVATE ${PODOFO_INCLUDE_DIR})
    target_link_libraries(${PROJECT_NAME} PRIVATE ${PODOFO_LIBRARY})
else ()
    find_path(PODOFO_INCLUDE_DIR podofo/podofo.h PATHS /usr/include /usr/local/include)
    find_library(PODOFO_LIBRARY NAMES podofo PATHS /usr/lib64 /usr/lib /usr/local/lib)
    target_include_directories(${PROJECT_NAME} PRIVATE ${PODOFO_INCLUDE_DIR})
    target_link_libraries(${PROJECT_NAME} PRIVATE ${PODOFO_LIBRARY})
endif (MSVC)
```
Is there something more I need to add for windows builds? I've looked at other windows projects using cmake-js, such as Microsofts napa.js and I dont see anything Im doing wrong concerning the use of cmake-js in my cmakelists file. Any help is very much appreciated. Thank you

**Comment by RSATom** [comment]
It could be just some dependency dll missing. You could use http://www.dependencywalker.com to find it out.

**Comment by Julusian** [comment]
This sounds like a missing dependency dll.
If you compiled it on a different machine then it could be missing the appropriate vs runtime dlls
