### ISSUE TITLE
Error: incorrect header check

### ISSUE THREAD

**Issue by Qix-** [cmake-js/cmake-js#142]
Having a problem compiling a new project using Electron 2.0.9/3.0.0-beta.

Looks like #24 is coming back. Might be a CDN/replication problem (I'm in the US, not China).

```
$ cmake-js compile --log-level verbose "${MYPROJECT_DEBUG:-'-D'}" -G Ninja --runtime electron --runtime-version="$(grep -oE 'ELECTRON_VERSION=[^
]+' Dockerfile | cut -d= -f2)" -O bin/native --arch x64
grep: brackets ([ ]) not balanced
verb CON Parsing arguments
verb CON options:
verb CON { directory: null,
verb CON   debug: false,
verb CON   cmakePath: null,
verb CON   generator: 'Ninja',
verb CON   toolset: undefined,
verb CON   target: undefined,
verb CON   preferMake: false,
verb CON   preferXcode: false,
verb CON   preferGnu: false,
verb CON   preferClang: false,
verb CON   std: null,
verb CON   runtime: 'electron',
verb CON   runtimeVersion: '',
verb CON   arch: 'x64',
verb CON   cMakeOptions: {},
verb CON   silent: false,
verb CON   out: 'bin/native' }
verb CON Running command: compile
verb CFG Looking for application level CMake.js config in '/src/myproject.
verb CFG Application level CMake.js config doesn't exists.
verb CFG Build system options:
verb CFG {"directory":"/src/myproject","debug":false,"cmakePath":null,"generator":"Ninja","preferMake":false,"preferXcode":false,"preferGnu":false,"preferClang":false,"std":null,"runtime":"electron","runtimeVersion":"","arch":"x64","cMakeOptions":{},"silent":false,"out":"bin/native"}
info TOOL Using Ninja generator, as specified from commandline.
info TOOL Using c++11 compiler standard.
verb TOOL Setting default OSX compiler flags.
info DIST Downloading distribution files.
http DIST 	- https://atom.io/download/atom-shell/v10.10.0/node-v10.10.0.tar.gz
ERR! OMG Error: incorrect header check
ERR! OMG     at Zlib.zlibOnError [as onerror] (zlib.js:153:17)
ERR! OMG Error: incorrect header check
ERR! OMG     at Zlib.zlibOnError [as onerror] (zlib.js:153:17)
error An unexpected error occurred: "Command failed.
```

Visiting that link directly redirects to `https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v10.10.0/node-v10.10.0.tar.gz` and shows:

```xml
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <Key>atom-shell/dist/v10.10.0/node-v10.10.0.tar.gz</Key>
  <RequestId>06877ADC9BDD20A5</RequestId>
  <HostId>Sox5ahfhPoreMhRxZdczLC3LZOtK9/FNAYHUgvjSQtPmAMwpHJolm0NgkVt3KNaYD+0CZZ/SHTE=</HostId>
</Error>
```

Is this a known issue, or something that has to be fixed on Electron's side?

**Comment by Qix-** [comment]
@unbornchikken how was the distribution URL found originally? I'd be willing to do some digging if I had some point in the right direction.

Is this something that's part of other electron packagers? Or maybe `electron-rebuild`?

**Comment by unbornchikken** [comment]
yup.

**Comment by Qix-** [comment]
Bugged a few people in the Electron slack about this, I have tried a number of things and can't figure out what's broken about it.

**Comment by Qix-** [comment]
Here's the response from @marshallofsound:

```
marshallofsound You’re issue is you are using nodes version to fetch electrons headers.  Use electrons version there instead

marshallofsound E.g. https://atom.io/download/atom-shell/v2.0.9/node-v2.0.9.tar.gz
```

**Comment by Qix-** [comment]
Just realized:

```
verb CON   runtimeVersion: '',
```

The grep command is yielding an empty string - cmake-js isn't validating the input in that way. Could that mean it's defaulting to a Node.js version?

**Comment by unbornchikken** [comment]
What's in package.json's cmake-js section?

**Comment by Dixeran** [comment]
Just ran into this. So it's necessary to both specify the runtime and runtime version, otherwise the download URL will be wrong.
E.g. `--runtime=electron --runtime-version=6.0.2`, while the 6.0.2 is acturally the Electron version, not the Node version Electron used.

**Comment by Minami-Kotori** [comment]
I'm having the same problem and it was working before electron 6.0.12

**Comment by Julusian** [comment]
sounds like this was cmake-js being called with the wrong parameters, do I dont see anything that needs to be done here
