### ISSUE TITLE
Error with using flag --log-level

### ISSUE THREAD

**Issue by dr15x86** [cmake-js/cmake-js#144]
When run cmake-js with flag --log-level with any value it crash:

    node ./bin/cmake-js print-configure --log-level http
    
    /tmp/cmake-js/bin/cmake-js:144
    if (argv.l && _.contains(logLevels, argv.l)) {
                    ^
    
    TypeError: _.contains is not a function
        at Object.<anonymous> (/tmp/cmake-js/bin/cmake-js:144:17)
        at Module._compile (internal/modules/cjs/loader.js:689:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        at Module.load (internal/modules/cjs/loader.js:599:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
        at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
        at startup (internal/bootstrap/node.js:279:19)
        at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)

In lodash@4 removed method `contains` and now need use method `includes`. For example, some error https://github.com/mgonto/restangular/issues/1298

cmake-js version cmake-js@4.0.0
now cmkae-js depend at lodash@4.17.11

**Comment by bonebizz21** [comment]
cool

**Comment by unbornchikken** [comment]
Fixed as of v4.0.1.
