### ISSUE TITLE
Cross-Compiling using Toolchain: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string.

### ISSUE THREAD

**Issue by clarkx86** [cmake-js/cmake-js#170]
Hello :-),
I'm trying to cross-compile for Windows on Ubuntu using a toolchain file ([this one](https://github.com/zyga/cmake-toolchains/blob/master/Toolchain-Ubuntu-mingw64.cmake)).
I specified it in the `package.json` as following:
```
[...]
"scripts": {
    "install": "cmake-js compile -m -DCMAKE_TOOLCHAIN_FILE=\"windows.toolchain\""
  },
[...]
```
but I get thrown the following error:
```
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Object.resolve (path.js:1080:7)
    at new CMake (/mnt/c/Users/clark/Cloud/Google Drive/Dokumente/GitHub/Projects/forked/node-leveldb-mcpe/node_modules/cmake-js/lib/es6/cMake.js:24:25)
    at new BuildSystem (/mnt/c/Users/clark/Cloud/Google Drive/Dokumente/GitHub/Projects/forked/node-leveldb-mcpe/node_modules/cmake-js/lib/es6/buildSystem.js:29:18)
    at Object.<anonymous> (/mnt/c/Users/clark/Cloud/Google Drive/Dokumente/GitHub/Projects/forked/node-leveldb-mcpe/node_modules/cmake-js/bin/cmake-js:206:19)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

I'm on node 10. Also, I'm very new to CMake and basically only need to cross-compile for a project that I can't compile on Windows natively. Maybe the `package.json` isn't even the right place to specify `-DCMAKE_TOOLCHAIN_FILE=\"windows.toolchain\""` in the first place?

Any help very much appreciated :), I'm stuck on this for weeks, trying to figure it out myself...

Thank you and have an amazing weekend,
- clarkx86

**Comment by clarkx86** [comment]
I should've read the readme better... Had to specify `--CDCMAKE_TOOLCHAIN_FILE=\"windows.cmake\"`!
