### ISSUE TITLE
Compiling NAN Module with MinGW in an electron app

### ISSUE THREAD

**Issue by gdorion** [cmake-js/cmake-js#200]
Hey guys,

I have been looking around a lot for an awnser or a similar issue, I was able to use the MinGW generators with cmake-js try to compile a NAN module to be loaded in my electron app. Cmake-js is able to compile my node module. But when it comes to the linking phase it keeps telling me this error:

`g++.exe: error: /DELAYLOAD:NODE.EXE: No such file or directory`

I have tries to set a fullpath to node. I have also read on the /DELAYLOAD feature and how people seem to go around it but without success. It works with vscompiler.

Here is the output of my compilation: 
```
> cmake-js --debug -G "MinGW Makefiles" rebuild --target mag_calibration

[ 'C:\\Program Files\\nodejs\\node.exe',
  'C:\\Users\\ARA BaseStation\\Documents\\Code\\skycontrol-react\\boomerang\\node_modules\\cmake-js\\bin\\cmake-js',
  '--debug',
  '-G',
  'MinGW Makefiles',
  'rebuild',
  '--target',
  'mag_calibration' ]
info TOOL Using MinGW Makefiles generator, as specified from commandline.
info CMD CLEAN
info RUN cmake -E remove_directory "C:\Users\ARA BaseStation\Documents\Code\skycontrol-react\boomerang\build"
info CMD CONFIGURE
info RUN cmake "C:\Users\ARA BaseStation\Documents\Code\skycontrol-react\boomerang" --no-warn-unused-cli -G"MinGW Makefiles" -DCMAKE_JS_VERSION="5.3.2" -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_RUNTIME_OUTPUT_DIRECTORY="C:\Users\ARA BaseStation\Documents\Code\skycontrol-react\boomerang\build" -DCMAKE_JS_INC="C:\Users\ARA BaseStation\.cmake-js\electron-x64\v5.0.6\include\node;C:\Users\ARA BaseStation\Documents\Code\skycontrol-react\boomerang\node_modules\nan" -DCMAKE_JS_SRC="C:/Users/ARA BaseStation/Documents/Code/skycontrol-react/boomerang/node_modules/cmake-js/lib/cpp/win_delay_load_hook.cc" -DNODE_RUNTIME="electron" -DNODE_RUNTIMEVERSION="5.0.6" -DNODE_ARCH="x64" -DCMAKE_JS_LIB="C:\Users\ARA BaseStation\.cmake-js\electron-x64\v5.0.6\x64\node.lib" -DCMAKE_SHARED_LINKER_FLAGS="/DELAYLOAD:NODE.EXE"
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: C:/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/ARA BaseStation/Documents/Code/skycontrol-react/boomerang/build
info CMD BUILD
info RUN cmake --build "C:\Users\ARA BaseStation\Documents\Code\skycontrol-react\boomerang\build" --config Debug --target mag_calibration
Scanning dependencies of target mag_calibration
[ 50%] Building CXX object mag-calibration/CMakeFiles/mag_calibration.dir/src/NativeExtension.cpp.obj
[ 50%] Building CXX object mag-calibration/CMakeFiles/mag_calibration.dir/src/mag_calibration_wrapper.cpp.obj
[ 50%] Building CXX object mag-calibration/CMakeFiles/mag_calibration.dir/src/mag_calibration.cpp.obj
[ 50%] Building CXX object mag-calibration/CMakeFiles/mag_calibration.dir/__/node_modules/cmake-js/lib/cpp/win_delay_load_hook.cc.obj
[100%] Linking CXX shared library ..\mag_calibration.node
g++.exe: error: /DELAYLOAD:NODE.EXE: No such file or directory
g++.exe: error: C:UsersARA BaseStation.cmake-jselectron-x64v5.0.6x64node.lib: No such file or directory
mag-calibration\CMakeFiles\mag_calibration.dir\build.make:134: recipe for target 'mag_calibration.node' failed
mingw32-make.exe[3]: *** [mag_calibration.node] Error 1
CMakeFiles\Makefile2:410: recipe for target 'mag-calibration/CMakeFiles/mag_calibration.dir/all' failed
mingw32-make.exe[2]: *** [mag-calibration/CMakeFiles/mag_calibration.dir/all] Error 2
CMakeFiles\Makefile2:417: recipe for target 'mag-calibration/CMakeFiles/mag_calibration.dir/rule' failed
mingw32-make.exe[1]: *** [mag-calibration/CMakeFiles/mag_calibration.dir/rule] Error 2
Makefile:254: recipe for target 'mag_calibration' failed
mingw32-make.exe: *** [mag_calibration] Error 2
ERR! OMG Process terminated: 2
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

Thanks a mega bunch.

**Comment by 5cript** [comment]
I am currently trying to accomplish the same thing, but I have my doubts, that even if cmake-js tried to support it, that the produced modules would be loadable.

I commented out the lines in 'toolset.js' to eliminate the error with the unknown linker option.

But upon loading the module, node just errors out with:
> Uncaught Error: Invalid access to memory location.

This isn't very suprising, since we are loading a C++ library compiled with mingw in MSVC compiled nodejs. Restricting yourself to n-api without the C++ wrapper doesnt work.

Excessive static linking , -Wl,--kill-at and generating a def file also isn't helping.

So unless you build nodejs etc yourself, I dont know what to do.
MSYS2 once had a nodejs package, but I dont think they support it anymore.
Its not in the package manager anymore.

**Comment by mjmacleod** [comment]
Did anyone ever make any further progress on this? I'm currently looking into trying to make a MinGW library work on electron so am interested in any pointers

**Comment by mjmacleod** [comment]
Just informational as not a cmake-js user, so don't need the cmake support, but as I struggled to figure all of this out (theres not much information/writeup about this available anywhere) putting this here for posterity in case its of use to anyone else.

I have managed to get our autotools based MinGW project/framework working as an addon that can be run in either node or electron. Our build script is [here](https://github.com/Gulden/gulden-official/blob/2.2_development/developer-tools/build_node.sh).

1. NAN is probably not a feasible option but n-api and node-addon-api (c++ wrapper) work fine, as well as parts of libuv if necessary, though best to used node-addon-api as much as possible.
node-addon-api generate interfaces through the stable  n-api C API so as long as you do things carefully/right it interoperates with the MSVC compiled node/electron fine even when compiled under MinGW.
2. You need to create a [.def file](https://github.com/Gulden/gulden-official/blob/2.2_development/developer-tools/node/node.def) with the symbols that you need from node.exe and then generate a .a file for it with dlltool which must be linked when compiling the dll
3. You can use dlltool's `-y` option to make the .a file delayload. Combined with including a [delay load hook](https://github.com/Gulden/gulden-official/blob/2.2_development/src/unity/djinni/support-lib/nodejs/win_delay_load_hook.cpp). This allows the addon to be called from any executable name instead of just node.exe
4. You of course want to statically link all dependencies

It would be nice if the symbol definitions (or def file) were obtainable from an official source instead of having to be manually generated, I opened a bug for this on [node-addon-api github](https://github.com/nodejs/node-addon-api/issues/720)

**Comment by riccardo89** [comment]
hi! 

with the insights of @mjmacleod (thanks a lot!!!) I have been able to compile a n-api node module (using node-addon-api) that links statically a few C libraries compiled on linux for windows with mingw compiler without dependencies on the VC toolchain, some advices here:

1) it is paramount to use n-api, otherwise there would be problems down the line, for instance while linking the generated .a file (from the .def), this will also make your modules node and electron version independent.

2) for windows app packaging I use **electronuserland/builder:wine**  and here you find my CMakeLists.txt file for one of my libs:

`
cmake_minimum_required(VERSION 3.9)
cmake_policy(SET CMP0042 NEW)
set (CMAKE_CXX_STANDARD 11)
add_definitions(-std=c++11)

# N-API DEFINITIONS
add_definitions(-DNAPI_VERSION=2)

project (mylib VERSION 1.0.0)

# check if wine is installed, in that case we are non linux
# but we are building for windows
execute_process(COMMAND wine --version
        WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
        OUTPUT_VARIABLE IS_WINE
        )

# CROSS PLATFORM
if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    option(USE_CLANG "build application with clang" ON)
    set(MAC TRUE)
    set(LIB_NAME ${PROJECT_NAME}-darwin-10.6-amd64.a)
    set(LIB_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/mac)
    add_definitions(-DDARWIN=1)
endif()

if ((${CMAKE_SYSTEM_NAME} MATCHES "Windows") OR (NOT IS_WINE STREQUAL ""))
    set(WIN TRUE)
    set(LIB_NAME ${PROJECT_NAME}-windows-7.0-amd64.lib)
    set(LIB_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/windows)

    # link windows specific delay load hook and node symbols definition lib
    set(WIN_DELAY_LOAD_HOOK ${CMAKE_CURRENT_SOURCE_DIR}/hook/win_delay_load_hook.cc)
    set(LIBNODE ${CMAKE_CURRENT_SOURCE_DIR}/libnode.a)
    
    # use win32 compiler otherwise in the final product the thread library for windows will be missing 
    # and the electron app won't be able to load the addon, furthermore you should also link libgcc and libstdc++
    # if your electron app uses an installer (e.g NSIS) you may also dynamically install these dlls on windows during 
    # electron app installation, your choice
    set(CMAKE_CXX_COMPILER "/usr/bin/x86_64-w64-mingw32-g++-win32")
    set(CMAKE_C_COMPILER "/usr/bin/x86_64-w64-mingw32-gcc-win32")
    set(CMAKE_CXX_STANDARD_LIBRARIES "-static-libgcc -static-libstdc++ ${CMAKE_CXX_STANDARD_LIBRARIES}")

    add_definitions(-DWIN=1)
endif()

if (${CMAKE_SYSTEM_NAME} MATCHES "Linux" AND (IS_WINE STREQUAL ""))
    option(USE_CLANG "build application with clang" ON)
    set(LINUX TRUE)
    set(LIB_NAME ${PROJECT_NAME}-linux-amd64.a)
    set(LIB_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/linux)
    add_definitions(-DLINUX=1)
endif()

# BUILD
file(GLOB SOURCE_FILES *.cc)

include_directories(${LIB_DIRECTORY})
link_directories(${LIB_DIRECTORY})

add_library(
  ${PROJECT_NAME} SHARED
  ${LIB_DIRECTORY}/${LIB_NAME}
  ${SOURCE_FILES}
  ${WIN_DELAY_LOAD_HOOK}
)

# INCLUDE N-API WRAPPERS
execute_process(COMMAND node -p "require('node-addon-api').include"
        WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
        OUTPUT_VARIABLE NODE_ADDON_API_DIR
        )
string(REPLACE "\n" "" NODE_ADDON_API_DIR ${NODE_ADDON_API_DIR})
string(REPLACE "\"" "" NODE_ADDON_API_DIR ${NODE_ADDON_API_DIR})
target_include_directories(${PROJECT_NAME} PRIVATE ${NODE_ADDON_API_DIR})

# FINALIZE
set_target_properties(${PROJECT_NAME} PROPERTIES POSITION_INDEPENDENT_CODE TRUE)
set_target_properties(${PROJECT_NAME} PROPERTIES PREFIX "" SUFFIX ".node")
target_include_directories(${PROJECT_NAME} PRIVATE ${CMAKE_JS_INC})
target_link_libraries(${PROJECT_NAME} ${LIB_DIRECTORY}/${LIB_NAME} ${LIBNODE} ${CMAKE_JS_LIB})
`

Hope this will help!!! ;)

**Comment by gdorionara** [comment]
This is great information. Thanks. I am curious about something thought, under the windows only section, did you manually copy the libnode.a?

Thanks.

**Comment by riccardo89** [comment]
Hi @gdorionara, you are welcome :)!!!

So as far as I have understood the def file is guaranteed to be pretty stable (hence the motivation for using n-api) so you may always use the same one, I have actually had a confirmation of this by updating my node version from node.js 10 to node.js 14 and by updating the NAPI version from 2 to 3, and the libraries kept working flawlessly without any update to the libnode.a (so by using the same .def file). 

By no means I am saying that there won't be situations where you may need an updated version of the def file (for instance use new features added to a newer node version), but in my case it was not needed, please if anyone knows more about it or it has automated it with CMAKE let us know!

**Comment by gdorionara** [comment]
@mjmacleod Gave up on this a while ago and kept using msvc. But now the project has resurfaced and the needs for MinGW is bigger than ever. 

Here is what I was able to do:

1. Took the def file here: [https://github.com/Gulden/gulden-official/blob/2.2_development/developer-tools/node/node.def](url) and generaged a libnode.a with MinGW64 dlltool using this command: `dlltool -d node.def -y libnode.a`
2. Added the win_delay_load_hook.cc to my project and compiled it.
```
#ifdef _MSC_VER

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif

#include <windows.h>

#include <delayimp.h>
#include <string.h>

static FARPROC WINAPI load_exe_hook(unsigned int event, DelayLoadInfo *info)
{
  HMODULE m;
  if (event != dliNotePreLoadLibrary)
    return NULL;

  if (_stricmp(info->szDll, "electron") != 0 &&
      _stricmp(info->szDll, "node.exe") != 0)
    return NULL;

  m = GetModuleHandle(NULL);
  return (FARPROC)m;
}

decltype(__pfnDliNotifyHook2) __pfnDliNotifyHook2 = load_exe_hook;

#endif
```
3. Link against it in my cmake, compile well, just keep getting stuck on the delayload error `g++.exe: error: /DELAYLOAD:NODE.EXE: No such file or directory` which is very odd to me.

Here is my cmake file: 
```

list(APPEND CMAKE_PREFIX_PATH ${CMAKE_CURRENT_SOURCE_DIR}/../../resources/artefacts/skycontrol-lib/lib/cmake)
find_package(skycontrol-lib 0.17.0 REQUIRED)

# define NPI_VERSION
add_definitions(-DNAPI_VERSION=3)

project(skycontrol_nodelib VERSION 1.0.0)

set(CMAKE_VERBOSE_MAKEFILE ON)
set(CMAKE_BUILD_TYPE RelWithDebInfo)

set(files controllers/base_controller.cpp
          skycontrol_lib_napi.cpp)

set(bellFiles controllers/bell/bell_controller.cpp
              controllers/bell/forward_flight.cpp)

if(${WHITELABEL} STREQUAL bell)
  list (APPEND files ${bellFiles})
endif()

if ((${CMAKE_SYSTEM_NAME} MATCHES "Windows") OR (NOT IS_WINE STREQUAL ""))
    # link windows specific delay load hook and node symbols definition lib
    set(WIN_DELAY_LOAD_HOOK ${CMAKE_CURRENT_SOURCE_DIR}/hook/win_delay_load_hook.cc)
    set(LIBNODE ${CMAKE_CURRENT_SOURCE_DIR}/hook/libnode.a)
endif()

add_library(${PROJECT_NAME}
            SHARED
            ${files}
            ${WIN_DELAY_LOAD_HOOK})

#Linux specific
if ( CMAKE_COMPILER_IS_GNUCC )
    target_compile_options(${PROJECT_NAME} PRIVATE "-Wunused-result")
endif()

# Make js module
set_target_properties(${PROJECT_NAME} PROPERTIES POSITION_INDEPENDENT_CODE TRUE)
set_target_properties(${PROJECT_NAME} PROPERTIES PREFIX "" SUFFIX ".node")

# White Labels
string(TOUPPER ${WHITELABEL} TO_UPPER_WHITELABEL)
target_compile_definitions(${PROJECT_NAME} PUBLIC ${TO_UPPER_WHITELABEL})

# INCLUDE N-API WRAPPERS
execute_process(COMMAND node -p "require('node-addon-api').include"
        WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
        OUTPUT_VARIABLE NODE_ADDON_API_DIR
        )
string(REPLACE "\n" "" NODE_ADDON_API_DIR ${NODE_ADDON_API_DIR})
string(REPLACE "\"" "" NODE_ADDON_API_DIR ${NODE_ADDON_API_DIR})
target_include_directories(${PROJECT_NAME} PRIVATE ${NODE_ADDON_API_DIR})

# FINALIZE
set_target_properties(${PROJECT_NAME} PROPERTIES POSITION_INDEPENDENT_CODE TRUE)
set_target_properties(${PROJECT_NAME} PROPERTIES PREFIX "" SUFFIX ".node")
target_include_directories(${PROJECT_NAME} PRIVATE ${CMAKE_JS_INC})
target_link_libraries(${PROJECT_NAME} skycontrol-lib ${LIBNODE} ${CMAKE_JS_LIB})
```

I used electron 11 (node12.8.0) and node-addon-api (v3) like you suggested. This makes all sense to me but for some reason I am missing something.

Any thoughts on a step that I am missing? I build on Windows 10 Pro using the mingw64 package.
Thanks a bunch!

**Comment by mjmacleod** [comment]
> @mjmacleod Gave up on this a while ago and kept using msvc. But now the project has resurfaced and the needs for MinGW is bigger than ever.
> Here is what I was able to do:
> <snip>
>     1. Link against it in my cmake, compile well, just keep getting stuck on the delayload error `g++.exe: error: /DELAYLOAD:NODE.EXE: No such file or directory` which is very odd to me.
This is likely your issue.

> I used electron 11 (node12.8.0) and node-addon-api (v3) like you suggested. This makes all sense to me but for some reason I am missing something.
> Any thoughts on a step that I am missing? I build on Windows 10 Pro using the mingw64 package.
> Thanks a bunch!
I don't use cmake-js myself but only ended up on this issue because it was the best hit on the internet for what I was trying to do at the time.
So I can only partially help in that I know how to do this and I know it can work, but I have no experience (or even desire really) to have it work with cmake-js specifically myself.
@riccardo89 may be better positioned to assist as he is at least using cmake, I'm just compiling things directly from an autotools driven build system, however...

The main point of the delay load hook and other dlltool stuff is to handle manually what "/DELAYLOAD:NODE.EXE" would normally handle on your behalf, so passing "/DELAYLOAD:NODE.EXE" is redundant and will cause errors.

cmake-js currently always adds this flag when it detects windows, you'll probably want to comment out these lines in your cmake-js repo to prevent it from doing so:
https://github.com/cmake-js/cmake-js/blob/master/lib/toolset.js#L149
https://github.com/cmake-js/cmake-js/blob/master/lib/toolset.js#L166

This should either work or at least get you a bit further to the next error.
To fix this properly, instead of manually commenting things out, "cmake-js" will probably have to be modified a bit so that it can detect mingw as the toolset and then not add those delayload arguments in that case (and ideally instead do all the dlltool stuff on the users behalf) - I guess a cmake-js developer may want to chime in on that though once you get there.

Hope that helps.

**Comment by caiiiycuk** [comment]
I tried this with electron v13.6.9 and napi 4. Everything compiles fine, but if i add `#include <napi.h>` then electron didn't load the module with error:
```
Error: The specified module could not be found.
some.node
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\caiiiycuk\dos.zone.browser.pc\src\index.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
```

If I dont' include napi, then electron says that module is not self registered.

**Comment by Kreijstal** [comment]
This would be nice to have, any progress?
