### ISSUE TITLE
Global/static initialization code not executed on modules for windows i.e. dlls

### ISSUE THREAD

**Issue by Superlokkus** [cmake-js/cmake-js#205]
While messing with a lot of problems in the vicinity of #204 I finally managed to reproduce and diagnose down a segmentation fault I had when using global const C++ containers, which have initialization code (I am talking about std::map and vectors allocating constructors for example).

I made a nice reproduce able example, the unit test will work as expected on linux and fail on windows, because of the constructor of an global namespace variable not executed: 
https://github.com/Superlokkus/spielwiese/tree/napi_linking_problems_statics

```
git clone git@github.com:Superlokkus/spielwiese.git
git checkout napi_linking_problems_statics 
yarn install
yarn test
```

Variable https://github.com/Superlokkus/spielwiese/blob/napi_linking_problems_statics/src/lib_name/include/lib_name/lib_name.hpp#L9 should be assigned 0.905, which will be done on linux but not on windows, which fails the unit test.

Of course I guess this is not cmake-js fault but, nodejs problem on how to load the DLL at runtime, and missing the dlls init, I am creating a ticket to link there because:

- It might be cmake-js fault by missing a flag for msvc to call the dll init code, see https://stackoverflow.com/questions/5114683/loading-dll-not-initializing-static-c-classes
- The nodejs community, still used on gyp usage, might first want to blame cmakejs on this, so a issue stating otherwise might shtored the process
- I might have missed something or done wrong in my project or missunderstanding something, so you could correct me much better

**Comment by Superlokkus** [comment]
This indeed seems to be a cmake-js problem since a gyp based project with the same code allegendly works: https://github.com/bzoz/31886_issue_test

**Comment by Superlokkus** [comment]
OK so now I went the extra mile and installed the security risk python 2.7 so that we can test it with the deprecated gyp: Suprise I wont build due to a gyp bug can I assume now you did not built it on windows?

> 
> marku@DESKTOP-FI7JA9G MINGW64 ~/development/31886_issue_test (master)
> $ yarn install
> yarn install v1.17.3
> [1/4] Resolving packages...
> success Already up-to-date.
> $ node-gyp rebuild
> 
> C:\Users\marku\development\31886_issue_test>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.8.0
> gyp info using node@10.16.3 | win32 | x64
> gyp http GET https://nodejs.org/download/release/v10.16.3/node-v10.16.3-headers.tar.gz
> gyp http 200 https://nodejs.org/download/release/v10.16.3/node-v10.16.3-headers.tar.gz
> gyp http GET https://nodejs.org/download/release/v10.16.3/SHASUMS256.txt
> gyp http GET https://nodejs.org/download/release/v10.16.3/win-x86/node.lib
> gyp http GET https://nodejs.org/download/release/v10.16.3/win-x64/node.lib
> gyp http 200 https://nodejs.org/download/release/v10.16.3/win-x64/node.lib
> gyp http 200 https://nodejs.org/download/release/v10.16.3/SHASUMS256.txt
> gyp http 200 https://nodejs.org/download/release/v10.16.3/win-x86/node.lib
> gyp info spawn C:\Python27\python.exe
> gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'msvs',
> gyp info spawn args   '-G',
> gyp info spawn args   'msvs_version=2015',
> gyp info spawn args   '-I',
> gyp info spawn args   'C:\\Users\\marku\\development\\31886_issue_test\\build\\config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   'C:\\Users\\marku\\.node-gyp\\10.16.3\\include\\node\\common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=C:\\Users\\marku\\.node-gyp\\10.16.3',
> gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
> gyp info spawn args   '-Dnode_lib_file=C:\\Users\\marku\\.node-gyp\\10.16.3\\<(target_arch)\\node.lib',
> gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\marku\\development\\31886_issue_test',
> gyp info spawn args   '-Dnode_engine=v8',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'C:\\Users\\marku\\development\\31886_issue_test\\build',
> gyp info spawn args   '-Goutput_dir=.' ]
> gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
> gyp info spawn args [ 'build/binding.sln',
> gyp info spawn args   '/clp:Verbosity=minimal',
> gyp info spawn args   '/nologo',
> gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
> gyp ERR! UNCAUGHT EXCEPTION
> gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
> gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
> gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
> gyp ERR! System Windows_NT 10.0.18363
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\marku\development\31886_issue_test
> gyp ERR! node -v v10.16.3
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! This is a bug in `node-gyp`.
> gyp ERR! Try to update node-gyp and file an Issue if it does not help:
> gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
> error Command failed with exit code 7.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> 
> marku@DESKTOP-FI7JA9G MINGW64 ~/development/31886_issue_test (master)
>

**Comment by brett19** [comment]
I also have encountered this issue.  I was able to work around it by setting "/OPT:NOREF" which disables the removal of 'never referenced functions and data'.  This seems to cause all the expected initialization code to run, but does lead to some odd questions about what VS is thinking, since the data itself is clearly referenced.

**Comment by brett19** [comment]
I also put together a simpler single-file reproduction:
https://github.com/brett19/cmakestaticsrepro
