### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by stiv-yakovenko** [cmake-js/cmake-js#207]
Trying simple example:

```
git clone https://github.com/cmake-js/cmake-js-tut-01-module
cd cmake-js-tut-01-module
npm i
```

and get this error:

```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated npmconf@2.1.3: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.

> cmake-js-tut-01-module@1.0.0 install /home/stiv/cmake-js-tut-01-module
> cmake-js compile

fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (/home/stiv/cmake-js-tut-01-module/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/stiv/cmake-js-tut-01-module/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/stiv/cmake-js-tut-01-module/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/stiv/cmake-js-tut-01-module/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cmake-js-tut-01-module@1.0.0 install: `cmake-js compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cmake-js-tut-01-module@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/stiv/.npm/_logs/2020-02-26T04_16_21_320Z-debug.log
```

**Comment by sebasas15** [comment]
if it is still helpful to anyone, just by upgrading cmake-js fixed the problem for me.

**Comment by Julusian** [comment]
This is an incompatibility with the version of cmake-js and node you are using. The solution is to update cmake-js
