### ISSUE TITLE
Package install cannot find <nan.h>

### ISSUE THREAD

**Issue by axkibe** [cmake-js/cmake-js#39]
In manual mode everything (building in from my source directory) works and builds fine. Now i tried to package it all up and do a test install on another machine and there cmake-js cannot find nan.h

My package.json looks like this:

```
{
  "name": "vtk",
  "version": "1.0.2",
  "description": "node.js bindings to VTK",
  "author": {
    "name": "Axel Kittenberger",
    "email": "axkibe@gmail.com"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/axkibe/node-vtk"
  },
  "main": "./index",
  "license": "BSD-3-Clause",
  "devDependencies": {
    "cmake-js": "^3.0.0",
    "nan": "^2.2.0"
  },
  "dependencies": {
    "cmake-js": "^3.0.0",
    "nan": "^2.2.0"
  },
  "scripts": {
    "install": "cmake-js compile"
  }
}
```

Trying to install it:

```
$ npm install vtk
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

> vtk@1.0.2 install /home/axel/nvtk/node_modules/vtk
> cmake-js compile

info TOOL Using Unix Makefiles generator.
info TOOL Using c++11 compiler standard.
info CMD CONFIGURE
info RUN cmake "/home/axel/nvtk/node_modules/vtk" --no-warn-unused-cli -G"Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/home/axel/nvtk/node_modules/vtk/build/Release" -DCMAKE_JS_INC="/home/axel/.cmake-js/node-x64/v5.5.0/include/node" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="5.5.0" -DNODE_ARCH="x64" -DCMAKE_CXX_FLAGS="-std=c++11"
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- The imported target "vtkCommonCoreTCL" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkCommonCoreTCL-6.1.so.6.1.0"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.1/VTKTargets.cmake"
but not all the files it references.

[Many more of reference fail Wanrs]

-- Configuring done
-- Generating done
-- Build files have been written to: /home/axel/nvtk/node_modules/vtk/build
info CMD BUILD
info RUN cmake --build "/home/axel/nvtk/node_modules/vtk/build" --config Release
Scanning dependencies of target node-vtk
[  0%] Building CXX object CMakeFiles/node-vtk.dir/src/vtkInteractorStyleTrackballCameraWrap.cc.o
/home/axel/nvtk/node_modules/vtk/src/vtkInteractorStyleTrackballCameraWrap.cc:6:17: fatal error: nan.h: No such file or directory
 #include <nan.h>
                 ^
compilation terminated.
CMakeFiles/node-vtk.dir/build.make:54: recipe for target 'CMakeFiles/node-vtk.dir/src/vtkInteractorStyleTrackballCameraWrap.cc.o' failed
make[2]: *** [CMakeFiles/node-vtk.dir/src/vtkInteractorStyleTrackballCameraWrap.cc.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/node-vtk.dir/all' failed
make[1]: *** [CMakeFiles/node-vtk.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
info REP Build has been failed, trying to do a full rebuild.
info CMD CLEAN
info RUN cmake -E remove_directory "/home/axel/nvtk/node_modules/vtk/build"
info CMD CONFIGURE
info RUN cmake "/home/axel/nvtk/node_modules/vtk" --no-warn-unused-cli -G"Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/home/axel/nvtk/node_modules/vtk/build/Release" -DCMAKE_JS_INC="/home/axel/.cmake-js/node-x64/v5.5.0/include/node" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="5.5.0" -DNODE_ARCH="x64" -DCMAKE_CXX_FLAGS="-std=c++11"
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- The imported target "vtkCommonCoreTCL" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkCommonCoreTCL-6.1.so.6.1.0"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.1/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtkCommonMathTCL" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkCommonMathTCL-6.1.so.6.1.0"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.1/VTKTargets.cmake"
but not all the files it references.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/axel/nvtk/node_modules/vtk/build
info CMD BUILD
info RUN cmake --build "/home/axel/nvtk/node_modules/vtk/build" --config Release
Scanning dependencies of target node-vtk
[  0%] Building CXX object CMakeFiles/node-vtk.dir/src/vtkInteractorStyleTrackballCameraWrap.cc.o
/home/axel/nvtk/node_modules/vtk/src/vtkInteractorStyleTrackballCameraWrap.cc:6:17: fatal error: nan.h: No such file or directory
 #include <nan.h>
                 ^
compilation terminated.
CMakeFiles/node-vtk.dir/build.make:54: recipe for target 'CMakeFiles/node-vtk.dir/src/vtkInteractorStyleTrackballCameraWrap.cc.o' failed
make[2]: *** [CMakeFiles/node-vtk.dir/src/vtkInteractorStyleTrackballCameraWrap.cc.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/node-vtk.dir/all' failed
make[1]: *** [CMakeFiles/node-vtk.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
ERR! OMG Process terminated: 2
npm WARN ENOENT ENOENT: no such file or directory, open '/home/axel/nvtk/package.json'
npm WARN EPACKAGEJSON nvtk No description
npm WARN EPACKAGEJSON nvtk No repository field.
npm WARN EPACKAGEJSON nvtk No README data
npm WARN EPACKAGEJSON nvtk No license field.
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "vtk"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! vtk@1.0.2 install: `cmake-js compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vtk@1.0.2 install script 'cmake-js compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vtk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cmake-js compile
npm ERR! You can get their info via:
npm ERR!     npm owner ls vtk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/axel/nvtk/npm-debug.log
```

I tried on that machine again manually cloning https://github.com/axkibe/node-vtk and running `./node_modules/.bin/cmake-js bulid` manually and that works again...

**Comment by axkibe** [comment]
PS: This is my CMakeLists.txt:
https://github.com/axkibe/node-vtk/blob/001b89bf2de66a9e603123c85f69a25834e0fa27/CMakeLists.txt

**Comment by axkibe** [comment]
I worked around by putting this into CMakeLists.txt:
```
include_directories(${CMAKE_JS_INC} ../nan)
```

**Comment by unbornchikken** [comment]
How should I reproduce this? If a make a project and require your https://github.com/axkibe/node-vtk module, then I get the above error, do I?

**Comment by axkibe** [comment]
npm install vtk

should produce this. I implemented the workaround already in git.

Unless I miss something any package with cmake-js and nan ought to fail when 'npm install' ing it without having it downloaded first

**Comment by unbornchikken** [comment]
Ain't reproducible at my side. Which version of node and npm are you using?

**Comment by axkibe** [comment]
Since vtk is huge and complicated I now created a simple more minimal test: https://github.com/axkibe/hellonanworld

```
test$ node -v
v5.3.0
test$ npm -v
3.5.3
test$ ls -al
total 28
drwxr-xr-x   2 axel axel  4096 Jan 27 09:28 .
drwxr-xr-x 136 axel axel 20480 Jan 27 09:28 ..
test$ npm install https://github.com/axkibe/hellonanworld
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

> hellonanworld@1.0.0 install /home/axel/node_modules/hellonanworld
> cmake-js compile

info TOOL Using Unix Makefiles generator.
info TOOL Using c++11 compiler standard.
info CMD CONFIGURE
info RUN cmake "/home/axel/node_modules/hellonanworld" --no-warn-unused-cli -G"Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/home/axel/node_modules/hellonanworld/build/Release" -DCMAKE_JS_INC="/home/axel/.cmake-js/node-x64/v5.3.0/include/node" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="5.3.0" -DNODE_ARCH="x64" -DCMAKE_CXX_FLAGS="-std=c++11"
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/axel/node_modules/hellonanworld/build
info CMD BUILD
info RUN cmake --build "/home/axel/node_modules/hellonanworld/build" --config Release
Scanning dependencies of target hellonanworld
[100%] Building CXX object CMakeFiles/hellonanworld.dir/src/init.cc.o
/home/axel/node_modules/hellonanworld/src/init.cc:1:17: fatal error: nan.h: No such file or directory
 #include <nan.h>
                 ^
compilation terminated.
CMakeFiles/hellonanworld.dir/build.make:54: recipe for target 'CMakeFiles/hellonanworld.dir/src/init.cc.o' failed
make[2]: *** [CMakeFiles/hellonanworld.dir/src/init.cc.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/hellonanworld.dir/all' failed
make[1]: *** [CMakeFiles/hellonanworld.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
info REP Build has been failed, trying to do a full rebuild.
info CMD CLEAN
info RUN cmake -E remove_directory "/home/axel/node_modules/hellonanworld/build"
info CMD CONFIGURE
info RUN cmake "/home/axel/node_modules/hellonanworld" --no-warn-unused-cli -G"Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/home/axel/node_modules/hellonanworld/build/Release" -DCMAKE_JS_INC="/home/axel/.cmake-js/node-x64/v5.3.0/include/node" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="5.3.0" -DNODE_ARCH="x64" -DCMAKE_CXX_FLAGS="-std=c++11"
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/axel/node_modules/hellonanworld/build
info CMD BUILD
info RUN cmake --build "/home/axel/node_modules/hellonanworld/build" --config Release
Scanning dependencies of target hellonanworld
[100%] Building CXX object CMakeFiles/hellonanworld.dir/src/init.cc.o
/home/axel/node_modules/hellonanworld/src/init.cc:1:17: fatal error: nan.h: No such file or directory
 #include <nan.h>
                 ^
compilation terminated.
CMakeFiles/hellonanworld.dir/build.make:54: recipe for target 'CMakeFiles/hellonanworld.dir/src/init.cc.o' failed
make[2]: *** [CMakeFiles/hellonanworld.dir/src/init.cc.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/hellonanworld.dir/all' failed
make[1]: *** [CMakeFiles/hellonanworld.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
ERR! OMG Process terminated: 2
npm WARN enoent ENOENT: no such file or directory, open '/home/axel/package.json'
npm WARN axel No description
npm WARN axel No repository field.
npm WARN axel No README data
npm WARN axel No license field.
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/axkibe/hellonanworld"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! hellonanworld@1.0.0 install: `cmake-js compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hellonanworld@1.0.0 install script 'cmake-js compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hellonanworld package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cmake-js compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hellonanworld
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hellonanworld
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/axel/test/npm-debug.log
test$ 
```

**Comment by unbornchikken** [comment]
Still ain't reproducible. If I install that module it of course fails, but not with missing nan error. It's because the code should like this (you've missed v8:: prefixes):

```c++
#include <nan.h>

void init( v8::Local<v8::Object> exports )
{
	fprintf( stderr, "helloWorld\n" );
}

NODE_MODULE( addon, init )
```

instead of yours. If I fix that, then you hello module installs flawlessly. I'm using latest *.* on Windows. So this might be a local problem. Please modify your hello module to use install script of:

```
cmake-js compile --log-level=silly
```

And put there the output.

**Comment by axkibe** [comment]
OK. BTW I tested on two different debian machines.

```
~$ cd test
test$ rm -rf *
test$ npm install https://github.com/axkibe/hellonanworld
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

> hellonanworld@1.0.0 install /home/axel/node_modules/hellonanworld
> cmake-js compile --log-level=silly

sill CON argv:
sill CON { _: [ 'compile' ],
sill CON   version: false,
sill CON   h: false,
sill CON   help: false,
sill CON   D: false,
sill CON   debug: false,
sill CON   m: false,
sill CON   'prefer-make': false,
sill CON   preferMake: false,
sill CON   x: false,                                                            
sill CON   'prefer-xcode': false,                                               
sill CON   preferXcode: false,
sill CON   g: false,
sill CON   'prefer-gnu': false,
sill CON   preferGnu: false,
sill CON   C: false,
sill CON   'prefer-clang': false,
sill CON   preferClang: false,
sill CON   o: false,
sill CON   prec11: false,
sill CON   'log-level': 'silly',
sill CON   l: 'silly',
sill CON   logLevel: 'silly',
sill CON   '$0': '../.bin/cmake-js',
sill CON   d: undefined,
sill CON   c: undefined,
sill CON   s: undefined,
sill CON   r: undefined,
sill CON   v: undefined,
sill CON   a: undefined }
verb CON Parsing arguments
verb CON options:
verb CON { directory: null,
verb CON   debug: false,
verb CON   cmakePath: null,
verb CON   preferMake: false,
verb CON   preferXcode: false,
verb CON   preferGnu: false,
verb CON   preferClang: false,
verb CON   std: null,
verb CON   runtime: undefined,
verb CON   runtimeVersion: undefined,
verb CON   arch: undefined }
verb CON Running command: compile
verb CFG Looking for application level CMake.js config in '/home/axel/node_modules/hellonanworld.
sill CFG Looking for package.json in: '/home/axel/node_modules/hellonanworld/package.json'.
sill CFG Loaded:
sill CFG {"_args":[["https://github.com/axkibe/hellonanworld","/home/axel"]],"_from":"git+https://github.com/axkibe/hellonanworld.git","_id":"hellonanworld@1.0.0","_inCache":true,"_installable":true,"_location":"/hellonanworld","_phantomChildren":{},"_requested":{"hosted":{"directUrl":"https://raw.githubusercontent.com/axkibe/hellonanworld/master/package.json","gitUrl":"git://github.com/axkibe/hellonanworld.git","httpsUrl":"git+https://github.com/axkibe/hellonanworld.git","shortcut":"github:axkibe/hellonanworld","ssh":"git@github.com:axkibe/hellonanworld.git","sshUrl":"git+ssh://git@github.com/axkibe/hellonanworld.git","type":"github"},"name":null,"raw":"https://github.com/axkibe/hellonanworld","rawSpec":"https://github.com/axkibe/hellonanworld","scope":null,"spec":"git+https://github.com/axkibe/hellonanworld.git","type":"hosted"},"_requiredBy":["#USER"],"_resolved":"git+https://github.com/axkibe/hellonanworld.git#b41e037d7c9fcc153c3d336fbc2d8787967c873b","_shasum":"eb6e8ac8866b0f74568219c65ba99f110c1f6f4b","_shrinkwrap":null,"_spec":"https://github.com/axkibe/hellonanworld","_where":"/home/axel","author":{"email":"axkibe@gmail.com","name":"Axel Kittenberger"},"bugs":{"url":"https://github.com/axkibe/hellonanworld/issues"},"dependencies":{"cmake-js":"^3.0.0","nan":"^2.2.0"},"description":"test package","devDependencies":{"cmake-js":"^3.0.0","nan":"^2.2.0"},"gitHead":"b41e037d7c9fcc153c3d336fbc2d8787967c873b","homepage":"https://github.com/axkibe/hellonanworld#readme","license":"MIT","main":"./index","name":"hellonanworld","optionalDependencies":{},"readme":"ERROR: No README data found!","repository":{"type":"git","url":"git+https://github.com/axkibe/hellonanworld.git"},"scripts":{"install":"cmake-js compile --log-level=silly"},"version":"1.0.0"}
sill CFG Config not found.
sill CFG Looking for parent path.
sill CFG Parent path: '/home/axel/node_modules'.
sill CFG Looking for package.json in: '/home/axel/node_modules/package.json'.
sill CFG 'package.json' not found.
sill CFG Looking for parent path.
sill CFG Parent path: '/home/axel'.
sill CFG Looking for package.json in: '/home/axel/package.json'.
sill CFG 'package.json' not found.
sill CFG Looking for parent path.
sill CFG Parent path: '/home'.
sill CFG Looking for package.json in: '/home/package.json'.
sill CFG 'package.json' not found.
sill CFG Looking for parent path.
sill CFG Parent path: '/'.
sill CFG Looking for package.json in: '/package.json'.
sill CFG 'package.json' not found.
sill CFG Looking for parent path.
sill CFG Parent path with package.json file doesn't exists. Done.
verb CFG Application level CMake.js config doesn't exists.
verb CFG Build system options:
verb CFG {"directory":"/home/axel/node_modules/hellonanworld","debug":false,"cmakePath":null,"preferMake":false,"preferXcode":false,"preferGnu":false,"preferClang":false,"std":null}
info TOOL Using Unix Makefiles generator.
info TOOL Using c++11 compiler standard.
info CMD CONFIGURE
info RUN cmake "/home/axel/node_modules/hellonanworld" --no-warn-unused-cli -G"Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/home/axel/node_modules/hellonanworld/build/Release" -DCMAKE_JS_INC="/home/axel/.cmake-js/node-x64/v5.3.0/include/node" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="5.3.0" -DNODE_ARCH="x64" -DCMAKE_CXX_FLAGS="-std=c++11"
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/axel/node_modules/hellonanworld/build
info CMD BUILD
info RUN cmake --build "/home/axel/node_modules/hellonanworld/build" --config Release
Scanning dependencies of target hellonanworld
[100%] Building CXX object CMakeFiles/hellonanworld.dir/src/init.cc.o
/home/axel/node_modules/hellonanworld/src/init.cc:1:17: fatal error: nan.h: No such file or directory
 #include <nan.h>
                 ^
compilation terminated.
CMakeFiles/hellonanworld.dir/build.make:54: recipe for target 'CMakeFiles/hellonanworld.dir/src/init.cc.o' failed
make[2]: *** [CMakeFiles/hellonanworld.dir/src/init.cc.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/hellonanworld.dir/all' failed
make[1]: *** [CMakeFiles/hellonanworld.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
info REP Build has been failed, trying to do a full rebuild.
info CMD CLEAN
info RUN cmake -E remove_directory "/home/axel/node_modules/hellonanworld/build"
info CMD CONFIGURE
info RUN cmake "/home/axel/node_modules/hellonanworld" --no-warn-unused-cli -G"Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/home/axel/node_modules/hellonanworld/build/Release" -DCMAKE_JS_INC="/home/axel/.cmake-js/node-x64/v5.3.0/include/node" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="5.3.0" -DNODE_ARCH="x64" -DCMAKE_CXX_FLAGS="-std=c++11"
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/axel/node_modules/hellonanworld/build
info CMD BUILD
info RUN cmake --build "/home/axel/node_modules/hellonanworld/build" --config Release
Scanning dependencies of target hellonanworld
[100%] Building CXX object CMakeFiles/hellonanworld.dir/src/init.cc.o
/home/axel/node_modules/hellonanworld/src/init.cc:1:17: fatal error: nan.h: No such file or directory
 #include <nan.h>
                 ^
compilation terminated.
CMakeFiles/hellonanworld.dir/build.make:54: recipe for target 'CMakeFiles/hellonanworld.dir/src/init.cc.o' failed
make[2]: *** [CMakeFiles/hellonanworld.dir/src/init.cc.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/hellonanworld.dir/all' failed
make[1]: *** [CMakeFiles/hellonanworld.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
ERR! OMG Error: Process terminated: 2
ERR! OMG     at ChildProcess.<anonymous> (/home/axel/node_modules/cmake-js/lib/es6/processHelpers.js:27:32)
ERR! OMG     at emitTwo (events.js:87:13)
ERR! OMG     at ChildProcess.emit (events.js:172:7)
ERR! OMG     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm WARN enoent ENOENT: no such file or directory, open '/home/axel/package.json'
npm WARN axel No description
npm WARN axel No repository field.
npm WARN axel No README data
npm WARN axel No license field.
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/axkibe/hellonanworld"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! hellonanworld@1.0.0 install: `cmake-js compile --log-level=silly`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hellonanworld@1.0.0 install script 'cmake-js compile --log-level=silly'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hellonanworld package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cmake-js compile --log-level=silly
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hellonanworld
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hellonanworld
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/axel/test/npm-debug.log
test$ 
```

**Comment by unbornchikken** [comment]
This is what I did.

- created an empty folder
- created a package.json file in it with a minimal content
- entered: npm install axkibe/hellonanworld

And it worked (or failed to compile because the prefix error described above).

**Comment by axkibe** [comment]
why a package.json? That shouldn't be needed

**Comment by axkibe** [comment]
PS: Maybe it finds <nan.h> somewhere else on your system? Or maybe its a Linux or Debian only problem?

**Comment by unbornchikken** [comment]
"why a package.json? That shouldn't be needed"

CMake.js assumes that every modules and their host application has a package.json file in their root folder. That assumption is driving the algorithm that try to find stuff like nan in application's dependency tree, which is kinda compilacted process with pre npm3. 

In the real world, every application and module **will** have a package.json file. Please do what I did, and see the result. I bet it's gonna get succeeded by that way.

**Comment by axkibe** [comment]
Ahja, even creating an absolute empty (0 size) package.json file where running "npm install.. " makes it work.

A package.json wasn't so far a requirement for node host applications. And I just googled around and there are some "Getting started guides" that go without.

If this requirement just cannot be lifted (which would be sad), even for "not real" people just experimenting with stuff, then at least make it output an error message about package.json missing. For example with VTK I expect people running tiny, rapid development scripts instead of making hugh "real" applications.

**Comment by unbornchikken** [comment]
I'm approving this as a feature request then. I'm gonna look for a way to work around this limitation as soon as I have some spare time. Thanks for reporting!

**Comment by unbornchikken** [comment]
3.1 has just got released. I've made a small change: a directory is considered as a Node.js application root when there is a node_modules folder in it. Does it satisfy your needs there?

**Comment by axkibe** [comment]
Doesn't pass the test below, but due to some other error?
It seems it can't find cmake-js binary.

```
~$ mkdir xtest
~$ cd xtest/
xtest$ npm install https://github.com/axkibe/hellonanworld
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

> hellonanworld@1.0.0 install /home/axel/node_modules/hellonanworld
> cmake-js compile --log-level=silly

: No such file or directory
npm WARN test@1.0.0 No repository field.
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/axkibe/hellonanworld"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! hellonanworld@1.0.0 install: `cmake-js compile --log-level=silly`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the hellonanworld@1.0.0 install script 'cmake-js compile --log-level=silly'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hellonanworld package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cmake-js compile --log-level=silly
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hellonanworld
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hellonanworld
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/axel/xtest/npm-debug.log
```

creating an empty node_modules directory makes the error different:
```
xtest$ mkdir node_modules
xtest$ npm install https://github.com/axkibe/hellonanworld                                                                
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

> hellonanworld@1.0.0 install /home/axel/xtest/node_modules/hellonanworld
> cmake-js compile --log-level=silly

: No such file or directory
npm WARN enoent ENOENT: no such file or directory, open '/home/axel/xtest/package.json'
npm WARN xtest No description
npm WARN xtest No repository field.
npm WARN xtest No README data
npm WARN xtest No license field.
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/axkibe/hellonanworld"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! hellonanworld@1.0.0 install: `cmake-js compile --log-level=silly`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the hellonanworld@1.0.0 install script 'cmake-js compile --log-level=silly'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hellonanworld package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cmake-js compile --log-level=silly
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hellonanworld
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hellonanworld
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/axel/xtest/npm-debug.log
xtest$ 
``

A user should be able to call "npm install bla" from a blank directory to kickstart his/her project. This has always been possible with standard npm and node-gyp.

**Comment by unbornchikken** [comment]
Yeah, that was my goal with the mentioned check. I'm gonna try to workaround this by another way though.

**Comment by briskycat** [comment]
This is still an issue with CMake.js 5.2.0.

**Comment by Julusian** [comment]
If this is still an issue being hit, then the 'solution' is simply to create a package.json
It sounds like it is working fine with modern versions of node
